# Generated by Django 2.2.28 on 2024-07-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='sustain',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='part',
            name='warmth',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='part',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
