# Generated by Django 2.2.28 on 2024-07-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='username',
            field=models.CharField(default='anonymous', max_length=30),
        ),
    ]
